#!/usr/bin/env python
from gevent import monkey; monkey.patch_all()
import argparse
import signal
import sys
from setproctitle import setproctitle; setproctitle('inboxapp-srv')

from inbox.server.config import config, load_config
from inbox.server.log import configure_logging, get_logger
log = get_logger()

def debug(args=None):
    """ Run the server with autoreload. TODO add debug flag to startup."""
    from werkzeug.serving import run_with_reloader
    run_with_reloader(start)

def start(args=None):
    # commit = subprocess.check_output(["git", "describe", "--tags"])
    print """
\033[94m     Welcome to... \033[0m\033[1;95m
      _____       _
     |_   _|     | |
       | |  _ __ | |__   _____  __
       | | | '_ \| '_ \ / _ \ \/ /
      _| |_| | | | |_) | (_) >  <
     |_____|_| |_|_.__/ \___/_/\_\\  \033[0m

     Use CTRL-C to stop.
     """
    from inbox.server.models import init_db
    init_db()

    # Start ZeroRPC api server service
    from inbox.server.util.concurrency import make_zerorpc
    from inbox.server.api import API

    api_srv_loc = config.get('API_SERVER_LOC', None)
    make_zerorpc(API, api_srv_loc)

    # Start ZeroRPC mail sync server service
    from inbox.server.sync import SyncService
    sync_srv_loc = config.get('CRISPIN_SERVER_LOC', None)
    make_zerorpc(SyncService, sync_srv_loc)


    # Start ZeroRPC contacts sync service
    from inbox.server.rolodex import ContactSync
    contacts_srv_loc = config.get('ROLODEX_SERVER_LOC', None)
    make_zerorpc(ContactSync, contacts_srv_loc)


    # start ZeroRPC search server service
    from inbox.server.search import SearchService
    search_srv_loc = config.get('SEARCH_SERVER_LOC', None)
    make_zerorpc(SearchService, search_srv_loc)

    # Start nginx like this. Restart with `-s reload` flags.
    # sudo nginx -c nginx.conf -p ./

    # Start web server
    from inbox.server.app import startserver
    try:
        startserver('127.0.0.1', 5000)
    except Exception, e:
        raise e
        stop(None)

def sync(args):
    import zerorpc

    c = zerorpc.Client(timeout=5)
    c.connect("tcp://127.0.0.1:9997")
    try:
        if args.cmd == 'start':
            print c.start_sync(args.email_address, dummy=args.dummy)
        elif args.cmd == 'startall':
            print c.start_sync(dummy=args.dummy)
        elif args.cmd == 'stop':
            print c.stop_sync(args.email_address)
        elif args.cmd == 'stopall':
            print c.stop_sync()
        elif args.cmd == 'status':
            print c.status()
        else:
            print >>sys.stderr, "No such command."
            sys.exit(1)
    except zerorpc.exceptions.TimeoutExpired:
        print >>sys.stderr, "Can't connect. Is the sync server running? (./inbox start)"
        sys.exit(1)


def stop(args):
    print """
\033[91m     Cleaning up...
\033[0m"""
    # from inbox.server.app import stopserver
    # stopserver()

    print """
\033[91m     Stopped.
\033[0m"""
    # os.system("stty echo")
    sys.exit(0)

def console(args):
    from inbox.server.console import start_console
    start_console(args.email_address)

def search(args):
    import zerorpc
    from inbox.server.models import db_session, User

    user = db_session.query(User).filter_by(g_email=args.email_address).one()

    try:
        c = zerorpc.Client(timeout=5)
        c.connect("tcp://127.0.0.1:9995")

        # XXX print something more useful here, like Subject: To: <snippet>
        # or something
        print c.search(user.id, args.query)
    except zerorpc.exceptions.TimeoutExpired:
        print >>sys.stderr, "Can't connect. Is the sync server running? (./inbox start)"
        sys.exit(1)

def index(args):
    from inbox.server.search import gen_search_index
    from inbox.server.models import db_session, User
    if args.email_address:
        gen_search_index(db_session.query(User).filter_by(
            g_email=args.email_address).one())
    else:
        for user in db_session.query(User).all():
            gen_search_index(user)

def signal_handler(signal, frame):
    stop(None)

def main():
    load_config()
    configure_logging()
    signal.signal(signal.SIGINT, signal_handler)

    parser = argparse.ArgumentParser(description="Inbox App")
    subparsers = parser.add_subparsers()

    parser_start = subparsers.add_parser('start')
    parser_start.set_defaults(func=start)

    parser_start = subparsers.add_parser('debug')
    parser_start.set_defaults(func=debug)

    parser_stop = subparsers.add_parser('stop')
    parser_stop.set_defaults(func=stop)

    parser_console = subparsers.add_parser('console', description="REPL for crispin")
    parser_console.add_argument('-e', '--email-address',
            help='Start console with crispin client for a particular user')
    parser_console.set_defaults(func=console)

    parser_sync = subparsers.add_parser('sync', description="Download initial mail metadata and parts.")
    parser_sync.add_argument('cmd', help='start or stop')
    parser_sync.add_argument('email_address', help='Email address of user to sync')
    parser_sync.add_argument('--dummy', action='store_true',
            help="Don't connect to IMAP backend.", default=False)
    parser_sync.set_defaults(func=sync)

    parser_sync = subparsers.add_parser('index', description="Index mail")
    parser_sync.add_argument('email_address',
            help='Email address of user to index mail')
    parser_sync.set_defaults(func=index)

    parser_sync = subparsers.add_parser('search', description="Search mail")
    parser_sync.add_argument('email_address',
            help='Email address of user to search mail')
    parser_sync.add_argument('query', help='Term(s) to search for')
    parser_sync.set_defaults(func=search)

    args = parser.parse_args()
    args.func(args)

if __name__=="__main__":
    main()
