#!/usr/bin/env python
from __future__ import absolute_import, print_function

import json
import os
import yaml
import sys

try:
    config = {}
    secrets = {}
    config['MYSQL_HOSTNAME'] = os.environ['MYSQL_PORT_3306_TCP_ADDR']
    config['MYSQL_PORT'] = int(os.environ['MYSQL_PORT_3306_TCP_PORT'])
    secrets['MYSQL_USER'] = 'root'
    secrets['MYSQL_PASSWORD'] = os.environ['MYSQL_ENV_MYSQL_ROOT_PASSWORD']
except KeyError:
    print("** Not using docker links to generate database config",
          file=sys.stderr)
else:
    os.umask(0o022)
    with open('/run/inboxapp/config.json', "w") as f:
        print(json.dumps(config, indent=True, sort_keys=True), file=f)
    os.umask(0o027)
    with open('/run/inboxapp/secrets.yml', "w") as f:
        yaml.safe_dump(secrets, stream=f)
