#!/bin/sh
# This gets executed from a Dockerfile after some source code has been ADDed to
# the current directory.
set -e

if [ -z "$1" ]; then
    echo >&2 "error: No directory specified"
    exit 1
fi

case "$1" in
    -*)
        echo >&2 "usage: $0 DIR"
        exit 1
        ;;
esac

cd "$1"

# Make sure "git rev-parse HEAD" can still work
if [ -e '.git' ]; then
    mkdir -p .git/objects && git rev-parse HEAD >/dev/null
fi

# Change the ownership & permissions on the source directory
chown -R admin .
chmod -R u=rwX,g=rX,o=rX .

# Install the package and its dependencies
sudo -u admin pip install -e .

# Clear out potentially stale .pyc files
# XXX: Is this necessary?
find . -name '*.pyc' -delete
