"""Clean up MessageMeta.

Revision ID: 274f2cdaa8db
Revises: 331a3cf84d2
Create Date: 2013-09-13 22:33:06.566473

"""

# revision identifiers, used by Alembic.
revision = '274f2cdaa8db'
down_revision = '331a3cf84d2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messagemeta', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('messagemeta', 'g_msgid',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('messagemeta', 'g_user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
    op.execute("UPDATE messagemeta, users SET messagemeta.user_id = users.id WHERE messagemeta.g_email = users.g_email")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messagemeta', 'g_user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('messagemeta', 'g_msgid',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('messagemeta', 'user_id')
    ### end Alembic commands ###
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
