"""Add sync_active flag to users.

Revision ID: 2fe1e83a4d73
Revises: 1d7229c6b257
Create Date: 2013-09-26 12:35:40.671560

"""

# revision identifiers, used by Alembic.
revision = '2fe1e83a4d73'
down_revision = '1d7229c6b257'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sync_active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sync_active')
    ### end Alembic commands ###
