"""Pull shared data out of FolderMeta.

Revision ID: 424b0c9dc77
Revises: 8ac04d897b2
Create Date: 2013-10-05 16:28:44.142030

"""

# revision identifiers, used by Alembic.
revision = '424b0c9dc77'
down_revision = '8ac04d897b2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foldermeta', sa.Column('messagemeta_id', sa.Integer(), nullable=False))
    op.add_column('foldermeta', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('foldermeta', u'g_email')
    op.drop_column('foldermeta', u'g_msgid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foldermeta', sa.Column(u'g_msgid', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('foldermeta', sa.Column(u'g_email', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('foldermeta', 'user_id')
    op.drop_column('foldermeta', 'messagemeta_id')
    ### end Alembic commands ###
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
