"""Add sync_host column to users.

Revision ID: 45c88613d742
Revises: 2fe1e83a4d73
Create Date: 2013-09-27 12:07:27.606652

"""

# revision identifiers, used by Alembic.
revision = '45c88613d742'
down_revision = '2fe1e83a4d73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sync_host', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sync_host')
    ### end Alembic commands ###
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
