"""Add save_raw_messages column to User.

Revision ID: 4cdb16c34f15
Revises: 45c88613d742
Create Date: 2013-09-27 15:10:52.087348

"""

# revision identifiers, used by Alembic.
revision = '4cdb16c34f15'
down_revision = '45c88613d742'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('save_raw_messages', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'save_raw_messages')
    ### end Alembic commands ###
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
