"""Add raw messages.

Revision ID: 5a384f700423
Revises: 294cd1b0969a
Create Date: 2013-09-26 11:05:38.855496

"""

# revision identifiers, used by Alembic.
revision = '5a384f700423'
down_revision = '294cd1b0969a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rawmessage',
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('data_sha256', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('internaldate', sa.DateTime(), nullable=True),
    sa.Column('g_msgid', sa.String(length=255), nullable=True),
    sa.Column('g_thrid', sa.String(length=255), nullable=True),
    sa.Column('folder_name', sa.String(length=255), nullable=True),
    sa.Column('msg_uid', sa.String(length=255), nullable=True),
    sa.Column('flags', mysql.MEDIUMBLOB, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'messagepart', u's3_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'messagepart', sa.Column(u's3_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_table('rawmessage')
    ### end Alembic commands ###
