"""Different way of handling attachments.

Revision ID: 66e904fb4aa
Revises: None
Create Date: 2013-09-10 18:18:52.974272

"""

# revision identifiers, used by Alembic.
revision = '66e904fb4aa'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'attachmentpart')
    op.add_column('messagepart', sa.Column('is_inboxapp_attachment', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messagepart', 'is_inboxapp_attachment')
    op.create_table(u'attachmentpart',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'g_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column(u'content_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column(u'content_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column(u'bytes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column(u'_misc_keyval', mysql.VARCHAR(length=255), nullable=True),
    sa.Column(u's3_id', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
