"""Pull shared data out of UIDValidity.

Revision ID: 8ac04d897b2
Revises: 4cdb16c34f15
Create Date: 2013-10-05 16:26:27.949540

"""

# revision identifiers, used by Alembic.
revision = '8ac04d897b2'
down_revision = '4cdb16c34f15'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uidvalidity', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('uidvalidity', u'g_email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uidvalidity', sa.Column(u'g_email', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('uidvalidity', 'user_id')
    ### end Alembic commands ###
