'''
This folder list was generated by aggregating examples of user folders
that were not properly labeled as trash, sent, or spam.
This list was constructed semi automatically, and manuallly verified.
Should we encounter problems with account folders in the future, add them
below to test for them.
'''


localized_folder_names = {
    'trash': {'Gel\xc3\xb6scht', 'Papierkorb',
              '\xd0\x9a\xd0\xbe\xd1\x80\xd0\xb7\xd0\xb8\xd0\xbd\xd0\xb0',
              '[Imap]/Trash', 'Papelera', 'Borradores',
              '[Imap]/\xd0\x9a\xd0\xbe\xd1\x80'
              '\xd0\xb7\xd0\xb8\xd0\xbd\xd0\xb0', 'Deleted Items',
              '\xd0\xa1\xd0\xbc\xd1\x96\xd1\x82\xd1\x82\xd1\x8f',
              'Papierkorb/Trash', 'Gel\xc3\xb6schte Elemente',
              'Deleted Messages', '[Gmail]/Trash', 'INBOX/Trash', 'Trash',
              'mail/TRASH', 'INBOX.Trash', 'INBOX.\xc9l\xe9ments supprim\xe9s',
              'INBOX.INBOX.Trash'},
    'spam': {'Roskaposti', 'INBOX.spam', 'INBOX.Spam', 'Skr\xc3\xa4ppost',
             'Spamverdacht', 'spam', 'Spam', '[Gmail]/Spam', '[Imap]/Spam',
             '\xe5\x9e\x83\xe5\x9c\xbe\xe9\x82\xae\xe4\xbb\xb6', 'Junk',
             'Junk Mail', 'Junk E-Mail'},
    'inbox': {u'INBOX'},
    'sent': {'Postausgang', 'INBOX.Gesendet', '[Gmail]/Sent Mail',
             '\xeb\xb3\xb4\xeb\x82\xbc\xed\x8e\xb8\xec\xa7\x80\xed\x95\xa8'
             'Elementos enviados', 'Sent', 'Sent Items', 'Sent Messages',
             'INBOX.Sent Messages', 'Odeslan\xc3\xa9', 'mail/sent-mail',
             'Ko\xc5\xa1', 'INBOX.SentMail', 'Gesendet',
             'Ko\xc5\xa1/Sent Items', 'Gesendete Elemente',
             'INBOX.\xc9l\xe9ments envoy\xe9s', 'INBOX.INBOX.Sent',}}
