#!/usr/bin/env python

from inbox.server.config import load_config
from inbox.util.db import drop_everything

import sys
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--config', dest='config', default='config.cfg')
    parser.add_argument('-u', '--with-users', action='store_true',
                        dest='with_users', default=False)
    args = parser.parse_args()
    load_config(args.config)
    from inbox.server.models import engine

    # Always keep the 'alembic_version' table
    keep_tables = ['alembic_version']
    reset_columns = {}

    # '--with-users' NOT specified
    if not args.with_users:
        keep_tables += ['user', 'namespace', 'account', 'imapaccount',
                       'user_session', 'easaccount']

        reset_columns = {'easaccount': ['eas_account_sync_key']}

    drop_everything(engine, keep_tables=keep_tables,
                    reset_columns=reset_columns)
    return 0

if __name__ == '__main__':
    sys.exit(main())
