drop table if exists foldermeta;
drop table if exists blockmeta;
drop table if exists collections;
drop table if exists messagemeta;
drop table if exists uidvalidity;
drop table if exists rawmessage;
drop table if exists namespace;
drop table if exists user_session;
drop table if exists user;
