#!/usr/bin/env python

from inbox.server.config import load_config
load_config()

from inbox.server.models import db_session, Message, Block

for msg in db_session.query(Message).join(Block):
    print msg.id,
    msg.calculate_sanitized_body()

db_session.commit()
