<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'InboxServerLintEngine' => 'src/InboxServerLintEngine.php',
    'MGArcanistPyLintLinter' => 'src/MGArcanistPyLintLinter.php',
    'PytestTestEngine' => 'src/PytestTestEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'InboxServerLintEngine' => 'ArcanistLintEngine',
    'MGArcanistPyLintLinter' => 'ArcanistLinter',
    'PytestTestEngine' => 'ArcanistBaseUnitTestEngine',
  ),
));
