#!/bin/bash
set -e

DIR="$( cd "$( dirname "$0" )" && pwd )"
echo "$DIR"

if [[ ! -f "$DIR"/server.key ]] ; then
    echo 'Generating self-signed keys for HTTPS...'

    # Generate a private key without a passphrase
	openssl genrsa -out "$DIR"/server.key 1024

	# Generate a CSR
	openssl req -new -key "$DIR"/server.key -out "$DIR"/server.csr -subj '/CN=development/O=FooCorp LTD./C=US'

	# Generate self signed certificate
	openssl x509 -req -days 365 -in "$DIR"/server.csr -signkey "$DIR"/server.key -out "$DIR"/server.crt

	rm "$DIR"/server.csr
fi


echo """
pid =

[https]
accept=443
connect=5555
cert="$DIR"/server.crt
key="$DIR"/server.key
""" > "$DIR"/dev_https


echo 'killing old stunnel...'
pkill stunnel4 &&  # ampersands fool set -e

echo 'Starting stunnel...'
stunnel4 "$DIR"/dev_https
